/* Generated by the Nim Compiler v2.2.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var F = {procname: "module dom", prev: framePtr, filename: "/Users/bung/nim-works/helix/src/helix/runtime/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/Users/bung/nim-works/helix/src/helix/runtime/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
